name: Run Tests

on:
    push:
        branches: [main, dev]
    pull_request:
        branches: [main, dev]
    workflow_dispatch:

jobs:
    integration-tests:
        runs-on: ubuntu-latest
        timeout-minutes: 45

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Python 3.13
              uses: actions/setup-python@v4
              with:
                  python-version: "3.13"

            - name: Install Rye
              uses: eifinger/setup-rye@v4
              with:
                  enable-cache: true
                  cache-prefix: "optional-prefix"

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Set up QEMU
              uses: docker/setup-qemu-action@v3

            - name: Verify Docker installation
              run: |
                  echo "Verifying Docker installation..."
                  docker --version
                  docker info
                  echo "Docker daemon is running and accessible"

            - name: Sync dependencies with Rye
              run: rye sync

            - name: Check test discovery
              run: |
                  echo "Discovering tests..."
                  rye run pytest --collect-only -q

            - name: Run tests with pytest-xdist (parallel execution)
              run: rye run pytest -n 4 --tb=short -v tests/integration
              env:
                  CONTAINER_ENGINE: docker
                  PYTHONPATH: ${{ github.workspace }}/src
                  DOCKER_HOST: unix:///var/run/docker.sock

            - name: Upload test results
              uses: actions/upload-artifact@v4
              if: always()
              with:
                  name: test-results
                  path: |
                      test-results.xml
                      htmlcov/
                  retention-days: 7
